# Generated by Django 5.2.11 on 2026-04-07 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste Manual')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historial_inventario', to='productos.producto')),
            ],
        ),
    ]
