# Generated by Django 5.2.11 on 2026-04-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_cambio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cambio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Recibido'),
        ),
    ]
