# Generated by Django 5.2.11 on 2026-04-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puntos',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntos Acumulados'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CAJERO', 'Cajero'), ('CLIENTE', 'Cliente')], default='CAJERO', max_length=10),
        ),
    ]
