# Generated by Django 5.2.11 on 2026-04-07 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_fk',
            new_name='categoria',
        ),
    ]
